// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"profile":{"path":"profile","id":"profile"},"index":{"path":"/","id":"index"}},
    routeComponents: {
'profile': React.lazy(() => import(/* webpackChunkName: "p__profile" */'../../pages/profile.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "p__index" */'../../pages/index.tsx')),
},
  };
}
